---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: app
  annotations:
    flux.weave.works/tag.flask: glob:develop-v*
    flux.weave.works/automated: 'true'
  labels:
    role: frontend
    env: demo
spec:
  replicas: 2
  selector:
    matchLabels:
      role: frontend
  template:
    metadata:
      labels:
        role: frontend
    spec:
      containers:
      - name: nginx
        image: nginx:1.18-perl
        imagePullPolicy: IfNotPresent
        ports:
        - name: http
          containerPort: 80
        volumeMounts:
        - name: nginx-proxy-config
          mountPath: /etc/nginx/conf.d/default.conf
          subPath: nginx.conf
      - name: flask
        image: jdk2588/gitops:develop-v0.0.2
        imagePullPolicy: IfNotPresent
        ports:
        - name: http
          containerPort: 5000
        env:
        - name: APP_NAME
          value: ONE2N
        - name: APP_VERSION
          value: v1
      volumes:
      - name: nginx-proxy-config
        configMap:
          name: nginx-conf
